// apps/frontend/src/lib/components/list-carousel.svelte
<script lang="ts">
  import * as Carousel from "$lib/components/ui/carousel/index.js";
  import ListItem from "./list-item.svelte";
  import PortraitCardSkeleton from "$lib/components/media/portrait-card-skeleton.svelte";

  let { data = $bindable(), indexer = undefined, type = "" } = $props();
</script>

{#if Array.isArray(data) && data.length > 0}
  <Carousel.Root
    opts={{
      dragFree: true,
      slidesToScroll: "auto",
    }}
    class="mt-0"
  >
    <Carousel.Content class="-ml-3">
      {#each data as item, i (item.id)}
        <Carousel.Item
          class="animate-in fade-in slide-in-from-bottom-8 fill-mode-backwards max-w-max pl-3 duration-700"
          style="animation-delay: {i * 50}ms"
        >
          <ListItem
            data={item}
            indexer={indexer || item.indexer}
            type={type || item.media_type || item.type}
            class="w-36 md:w-44 lg:w-48"
          />
        </Carousel.Item>
      {/each}
    </Carousel.Content>
  </Carousel.Root>
{:else}
  <div class="mt-1.5 flex gap-3 overflow-x-auto pb-2">
    {#each Array.from({ length: 6 }, (__, i) => i) as i (i)}
      <div class="w-36 flex-none md:w-44 lg:w-48">
        <PortraitCardSkeleton />
      </div>
    {/each}
  </div>
{/if}

// apps/frontend/components/media/list-carousel.tsx
import { type ComponentProps, Suspense, use } from "react";
import { ErrorBoundary } from "react-error-boundary";

import {
  Carousel,
  CarouselContent,
  CarouselItem,
  CarouselNext,
  CarouselPrevious,
} from "../ui/carousel";
import { ListItem } from "./list-item";
import { PortraitCardSkeleton } from "./portrait-card-skeleton";

interface ListCarouselProps {
  itemsPromise: Promise<ComponentProps<typeof ListItem>["mediaItem"][]>;
  indexer: string | undefined;
}

function ListCarouselSkeleton() {
  return (
    <div className="mt-1.5 flex gap-3 overflow-x-auto pb-2">
      {Array.from({ length: 6 }, (_, i) => i).map((i) => (
        <div key={i} className="w-36 flex-none md:w-44 lg:w-48">
          <PortraitCardSkeleton />
        </div>
      ))}
    </div>
  );
}

function ListCarouselInner({ itemsPromise, indexer }: ListCarouselProps) {
  const items = use(itemsPromise);

  return (
    <Carousel
      opts={{
        dragFree: true,
        slidesToScroll: "auto",
      }}
      className="mt-0"
    >
      <CarouselContent className="-ml-3">
        {items.map((item, i) => (
          <CarouselItem
            key={item.id}
            className="animate-in fade-in slide-in-from-bottom-8 fill-mode-backwards max-w-max pl-3 duration-700 basis-1/3"
            style={{ animationDelay: `${(i * 50).toString()}ms` }}
          >
            <ListItem
              mediaItem={item}
              indexer={indexer}
              className="w-36 md:w-44 lg:w-48"
            />
          </CarouselItem>
        ))}
      </CarouselContent>
      <CarouselPrevious />
      <CarouselNext />
    </Carousel>
  );
}

export function ListCarousel(props: ListCarouselProps) {
  return (
    <ErrorBoundary FallbackComponent={() => <div>Error loading items</div>}>
      <Suspense fallback={<ListCarouselSkeleton />}>
        <ListCarouselInner {...props} />
      </Suspense>
    </ErrorBoundary>
  );
}
