// apps/frontend/components/theme-switcher.svelte
<script lang="ts">
    import { setTheme, theme } from "mode-watcher";
    import Pallete from "@lucide/svelte/icons/palette";
    import Check from "@lucide/svelte/icons/check";
    import { Button } from "@/components/ui/button";
    import * as DropdownMenu from "@/components/ui/dropdown-menu";

    const themes = {
        amberminimal: "Amber Minimal",
        amethysthaze: "Amethyst Haze",
        bubblegum: "Bubblegum",
        caffeine: "Caffeine",
        catppuccin: "Catppuccin",
        cyberpunk: "Cyberpunk",
        darkmatter: "Dark Matter",
        doom64: "Doom 64",
        galacticglitch: "Galactic Glitch",
        graphite: "Graphite",
        mochamousse: "Mocha Mousse",
        mono: "Mono",
        neobrutalism: "Neo Brutalism",
        solardusk: "Solar Dusk",
        "t3-chat": "T3 Chat"
    };
</script>

<DropdownMenu.Root>
    <DropdownMenu.Trigger>
        {#snippet child({ props })}
            <Button variant="ghost" size="icon" aria-label="Change Theme" {...props}>
                <Pallete />
            </Button>
        {/snippet}
    </DropdownMenu.Trigger>
    <DropdownMenu.Content
        side="right"
        align="end"
        class="rounded-2xl border border-white/10 bg-zinc-950/95 shadow-2xl shadow-black/50 backdrop-blur-2xl">
        <DropdownMenu.Group class="space-y-1 p-2">
            <DropdownMenu.Label>La Pallete</DropdownMenu.Label>
            <DropdownMenu.Separator />
            {#each Object.entries(themes) as [key, name] (key)}
                <DropdownMenu.Item
                    class="flex items-center justify-between {theme.current === key
                        ? 'bg-accent/80 hover:bg-accent/90'
                        : 'hover:bg-accent/80'}"
                    onclick={() => {
                        setTheme(key);
                    }}>
                    <span>{name}</span>
                    {#if theme.current === key}
                        <Check class="ml-2 size-4" />
                    {/if}
                </DropdownMenu.Item>
            {/each}
        </DropdownMenu.Group>
    </DropdownMenu.Content>
</DropdownMenu.Root>

// apps/frontend/components/theme-switcher/theme-switcher.tsx
import { Button } from "@/components/_ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/_ui/dropdown-menu";
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/components/_ui/tooltip";
import { themes } from "@/components/providers/theme-provider";

import { cn } from "cn";
import { Check, Palette } from "lucide-react";
import { useTheme } from "next-themes";

export function ThemeSwitcher() {
  const { setTheme, theme } = useTheme();

  return (
    <DropdownMenu>
      <Tooltip>
        <TooltipTrigger asChild>
          <DropdownMenuTrigger asChild>
            <Button variant="ghost" size="icon" aria-label="Change Theme">
              <Palette />
            </Button>
          </DropdownMenuTrigger>
        </TooltipTrigger>
        <TooltipContent side="right">Switch theme</TooltipContent>
      </Tooltip>
      <DropdownMenuContent
        side="right"
        align="end"
        className="rounded-2xl border border-white/10 bg-zinc-950/95 shadow-2xl shadow-black/50 backdrop-blur-2xl"
      >
        <DropdownMenuGroup className="space-y-1 p-2">
          <DropdownMenuLabel>Themes</DropdownMenuLabel>
          <DropdownMenuSeparator />
          {Object.entries(themes).map(([key, name]) => (
            <DropdownMenuItem
              key={key}
              className={cn(
                "flex items-center justify-between",
                theme === key
                  ? "bg-accent/80 hover:bg-accent/90"
                  : "hover:bg-accent/80",
              )}
              onClick={() => {
                setTheme(key);
              }}
            >
              <span>{name}</span>
              {theme === key && <Check className="ml-2 size-4" />}
            </DropdownMenuItem>
          ))}
        </DropdownMenuGroup>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
