// apps/frontend/app/(protected)/details/media/[type]/[id]/_components/season-selector.tsx
import { Checkbox } from "@/components/_ui/checkbox";
import { Field, FieldGroup, FieldLabel } from "@/components/_ui/field";

import { cn } from "cn";
import { useFormContext } from "react-hook-form";

import type { HTMLAttributes } from "react";

export interface SeasonData {
  id: string;
  seasonNumber: number;
  name: string;
  completedCount: number;
  episodeCount: number;
  image: string | null;
}

interface SeasonSelectorProps extends Pick<
  HTMLAttributes<HTMLDivElement>,
  "className"
> {
  seasons: SeasonData[];
  requestedSeasons: Set<number>;
}

export function SeasonSelector({
  className,
  seasons,
  requestedSeasons,
}: SeasonSelectorProps) {
  const { register, setValue } = useFormContext();

  return (
    <div
      className={cn(
        className,
        "flex max-h-60 w-full flex-col gap-0.5 overflow-y-auto",
      )}
    >
      <div className="flex items-center justify-end">
        <button
          type="button"
          className="text-xs text-zinc-400 transition hover:text-zinc-200 disabled:cursor-not-allowed disabled:opacity-50"
          onClick={() => {
            // selectedSeasonNums =
            //   selectedSeasonNums.length > 0
            //     ? []
            //     : [...requestableSeasons];
          }}
          // disabled={requestableSeasons.length === 0}
        >
          {/* {selectedSeasonNums.length > 0 ? "Deselect all" : "Select all"} */}
        </button>
      </div>
      {seasons.map((season) => {
        const isPreviouslyRequested = requestedSeasons.has(season.seasonNumber);

        function renderContent() {
          if (isPreviouslyRequested) {
            return (
              <span className="text-xs font-normal opacity-70">Requested</span>
            );
          }

          if (season.completedCount < season.episodeCount) {
            return (
              <span className="text-muted-foreground text-xs font-normal opacity-70">
                {season.completedCount}/{season.episodeCount} eps
              </span>
            );
          }

          return (
            <span className="text-muted-foreground text-xs font-normal opacity-70">
              {season.episodeCount} eps
            </span>
          );
        }

        const name =
          `requestedSeasons[${season.seasonNumber.toString()}]` as const;

        return (
          <FieldGroup key={season.id}>
            <Field orientation="horizontal">
              <Checkbox
                {...register(name, { disabled: isPreviouslyRequested })}
                id={name}
                defaultChecked={isPreviouslyRequested}
                onCheckedChange={(checked) => {
                  setValue(name, checked, { shouldDirty: true });
                }}
                value="1"
              />
              <FieldLabel htmlFor={name}>
                <span>Season {season.seasonNumber}</span>
              </FieldLabel>
              {renderContent()}
            </Field>
          </FieldGroup>
        );
      })}
    </div>
  );
}

// apps/frontend/src/lib/components/media/riven/season-selector.svelte
<script lang="ts">
  export interface SeasonInfo {
    id: number;
    season_number: number;
    episode_count: number;
    completed_count?: number;
    name: string;
    status?: string;
  }

  interface Props {
    seasons: SeasonInfo[];
    selectedSeasons: number[];
    onToggle: (seasonNumber: number) => void;
    class?: string;
  }

  let {
    seasons,
    selectedSeasons,
    onToggle,
    class: className = "",
  }: Props = $props();

  function isSeasonLocked(season: SeasonInfo): boolean {
    return season.status === "Available";
  }
</script>

<div class="{className} flex max-h-60 w-full flex-col gap-0.5 overflow-y-auto">
  {#each seasons as season (season.id)}
    {@const locked = isSeasonLocked(season)}
    {@const selected = selectedSeasons.includes(season.season_number)}
    <button
      class="group hover:bg-muted/30 flex w-full items-center justify-between rounded-md px-3 py-1.5 text-sm transition-all {locked
        ? 'cursor-not-allowed opacity-50'
        : 'cursor-pointer'} {selected && !locked
        ? 'text-primary font-bold'
        : 'text-foreground font-medium'}"
      onclick={() => {
        onToggle(season.season_number);
      }}
      disabled={locked}
      title={season.name}
    >
      <span>Season {season.season_number}</span>

      {#if locked}
        <span class="text-xs font-normal opacity-70">Complete</span>
      {:else if season.completed_count != null && season.episode_count > 0}
        <span class="text-muted-foreground text-xs font-normal opacity-70"
          >{season.completed_count}/{season.episode_count} eps</span
        >
      {:else}
        <span class="text-muted-foreground text-xs font-normal opacity-70"
          >{season.episode_count} eps</span
        >
      {/if}
    </button>
  {/each}
</div>
