// apps/frontend/components/page-shell/page-shell.tsx
import { cn } from "cn";

import { fly } from "../_animations/fly";

import type { HTMLAttributes } from "react";

export function PageShell({
  className,
  children,
  ...restProps
}: HTMLAttributes<HTMLElement>) {
  return (
    <main
      className={cn(
        "mt-4 flex flex-col gap-6 p-4 pb-24 md:mt-14 md:gap-8 md:p-8 md:px-16 duration-600",
        fly,
        className,
      )}
      {...restProps}
    >
      {children}
    </main>
  );
}

// apps/frontend/src/lib/components/page-shell.svelte
<script lang="ts">
  import { cn } from "$lib/utils";
  import { fly } from "svelte/transition";
  import { cubicOut } from "svelte/easing";
  import type { HTMLAttributes } from "svelte/elements";

  let {
    class: className,
    children,
    ...restProps
  }: HTMLAttributes<HTMLElement> = $props();
</script>

<main
  in:fly|global={{ y: 20, duration: 600, easing: cubicOut }}
  class={cn(
    "mt-4 flex flex-col gap-6 p-4 pb-24 md:mt-14 md:gap-8 md:p-8 md:px-16",
    className,
  )}
  {...restProps}
>
  {@render children?.()}
</main>
