// apps/frontend/src/lib/components/tmdb-now-playing.svelte
<script lang="ts">
  import * as Carousel from "$lib/components/ui/carousel/index.js";
  import { fly } from "svelte/transition";
  import { cubicOut } from "svelte/easing";
  import { type CarouselAPI } from "$lib/components/ui/carousel/context.js";
  import Autoplay from "embla-carousel-autoplay";
  import { TMDB_IMAGE_BASE_URL, TMDB_GENRES } from "$lib/indexer-constants";
  import { gqlClient } from "$lib/graphql-client";
  import { getSeasonAndYear } from "$lib/helpers";
  import { Button } from "$lib/components/ui/button/index.js";
  import { Skeleton } from "$lib/components/ui/skeleton/index.js";
  import { getRatings } from "$lib/stores/ratings";
  import { Star } from "@lucide/svelte";

  export interface TMDBNowPlayingItem {
    id: number;
    media_type?: "movie" | "tv" | "person" | "company";
    title?: string;
    name?: string;
    backdrop_path?: string | null;
    release_date?: string;
    first_air_date?: string;
    vote_average?: number | null;
    original_language?: string;
    overview?: string;
    genre_ids?: number[];
    certification?: string;
  }

  interface Props {
    data?: TMDBNowPlayingItem[];
    showRequestButton?: boolean;
    alignment?: "left" | "center" | "right";
    heightClass?: string;
  }

  let {
    data = [],
    showRequestButton = true,
    alignment = "left",
    heightClass = "h-[350px] md:h-[420px]",
  }: Props = $props();

  let api = $state<CarouselAPI>();
  const autoplayDelay = 5000;
  let autoplayPlugin = Autoplay({
    delay: autoplayDelay,
    stopOnInteraction: false,
  });

  let currentIndex = $state(0);
  let logos = $state<Record<number, string | null>>({});
  let ratings = $state<
    Record<
      number,
      {
        scores?: {
          name: string;
          image?: string;
          score: string;
          url: string;
        }[];
      }
    >
  >({});
  let certifications = $state<Record<number, string | null>>({});

  // Handle carousel API events with proper cleanup using $effect.pre
  // This is the appropriate Svelte 5 pattern for subscribing to external events
  // when reacting to state changes (api becoming available)
  $effect.pre(() => {
    if (!api) return;

    const onSelect = () => {
      currentIndex = api!.selectedScrollSnap();
    };

    // Initialize current index and register event handler
    currentIndex = api.selectedScrollSnap();
    api.on("select", onSelect);

    // Cleanup: remove event handler when api changes or component unmounts
    return () => {
      api?.off("select", onSelect);
    };
  });

  async function loadItemData(item: TMDBNowPlayingItem) {
    // Fetch Ratings (independent of logo)
    if (ratings[item.id] === undefined) {
      const mediaType = item.media_type === "tv" ? "tv" : "movie";
      getRatings(item.id, mediaType)
        .then((data) => {
          ratings[item.id] = data;
        })
        .catch(() => {
          ratings[item.id] = { scores: [] };
        });
    }

    // Fetch Logo & Certification
    if (logos[item.id] !== undefined) return;

    const mediaType = item.media_type === "tv" ? "tv" : "movie";
    try {
      const result = await gqlClient<{
        tmdbLogoAndCert: { logo: string | null; certification: string | null };
      }>(
        `query TmdbLogoAndCert($type: String!, $id: Int!) {
                    tmdbLogoAndCert(type: $type, id: $id) { logo certification }
                }`,
        { type: mediaType, id: item.id },
      );
      const data = result.tmdbLogoAndCert;

      // Set certification if available
      if (data.certification) {
        certifications[item.id] = data.certification;
      } else {
        certifications[item.id] = null;
      }

      if (data.logo) {
        const img = new Image();
        img.src = data.logo;
        img.onload = () => {
          logos[item.id] = data.logo;
        };
        img.onerror = () => {
          logos[item.id] = null;
        };
      } else {
        logos[item.id] = null;
      }
    } catch (e) {
      console.error("Failed to fetch logo/cert", e);
      logos[item.id] = null;
    }
  }

  $effect(() => {
    if (!data.length) {
      return;
    }

    // 1. Load current item immediately
    const currentItem = data[currentIndex];
    if (currentItem) {
      void loadItemData(currentItem);
    }

    // 2. Load next/prev items (priority)
    const nextIndex = (currentIndex + 1) % data.length;
    const prevIndex = (currentIndex - 1 + data.length) % data.length;

    if (data[nextIndex]) {
      void loadItemData(data[nextIndex]);
    }

    if (data[prevIndex]) {
      void loadItemData(data[prevIndex]);
    }

    // 3. Load the rest in background with a slight delay/idle check
    // Using a simple timeout to defer non-critical fetches
    const timer = setTimeout(() => {
      data.forEach((item, index) => {
        if (
          index !== currentIndex &&
          index !== nextIndex &&
          index !== prevIndex &&
          logos[item.id] === undefined
        ) {
          void loadItemData(item);
        }
      });
    }, 1000);

    return () => {
      clearTimeout(timer);
    };
  });

  function getAlignmentClasses(
    align: "left" | "center" | "right",
    type: "container" | "flex",
  ): string {
    if (type === "container") {
      switch (align) {
        case "right":
          return "items-end text-right";
        case "center":
          return "items-center text-center";
        default:
          return "items-start text-left";
      }
    } else {
      switch (align) {
        case "right":
          return "justify-end";
        case "center":
          return "justify-center";
        default:
          return "justify-start";
      }
    }
  }
</script>

{#if Array.isArray(data) && data.length > 0}
  <div
    class="border-border/50 relative overflow-hidden rounded-2xl border shadow-2xl"
  >
    <Carousel.Root
      setApi={(emblaApi) => (api = emblaApi)}
      plugins={[autoplayPlugin]}
      opts={{ loop: true }}
      class="relative"
      role="region"
      aria-label="Now playing movies carousel"
    >
      <Carousel.Content>
        {#each data as item, index (item.id)}
          {@const isTV = item.media_type === "tv"}
          {@const mediaType = isTV ? "tv" : "movie"}
          {@const displayTitle = item.title ?? item.name ?? "Untitled"}
          <Carousel.Item class="relative w-full {heightClass}">
            <!-- Backdrop Image -->
            <img
              src={item.backdrop_path?.startsWith("http")
                ? item.backdrop_path
                : `${TMDB_IMAGE_BASE_URL}/original${item.backdrop_path}`}
              alt={displayTitle}
              class="h-full w-full object-cover object-top select-none"
              loading="lazy"
            />

            <!-- Gradient Overlay with dramatic landscape-card style mask -->
            <div
              class="bg-background pointer-events-none absolute top-0 right-0 bottom-0 left-0"
              style="-webkit-mask-image: radial-gradient(120% 160% at 0% 100%, black 0%, transparent 70%), linear-gradient(to bottom, transparent 10%, black 100%); mask-image: radial-gradient(120% 160% at 0% 100%, black 0%, transparent 70%), linear-gradient(to bottom, transparent 10%, black 100%);"
            ></div>

            <!-- Text Content with Netflix-style reveal -->
            {#key currentIndex === index ? currentIndex : -1}
              <div
                class="absolute top-0 right-0 bottom-0 left-0 z-10 flex flex-col justify-end px-8 pt-2 pb-24 md:px-32 md:pt-8 md:pb-16 lg:right-0 lg:left-0 {getAlignmentClasses(
                  alignment,
                  'container',
                )}"
              >
                <div
                  class="flex w-full max-w-3xl flex-col {alignment === 'right'
                    ? 'items-end'
                    : alignment === 'center'
                      ? 'items-center'
                      : 'items-start'}"
                >
                  <!-- Title / Logo -->
                  <div
                    class="mb-4 flex h-24 items-end {getAlignmentClasses(
                      alignment,
                      'flex',
                    )}"
                  >
                    {#if logos[item.id]}
                      <img
                        src={logos[item.id]}
                        alt={displayTitle}
                        in:fly={{
                          y: 20,
                          duration: 1000,
                          delay: 100,
                          easing: cubicOut,
                        }}
                        class="max-h-full max-w-[80%] object-contain drop-shadow-2xl {alignment ===
                        'right'
                          ? 'object-bottom-right'
                          : alignment === 'center'
                            ? 'object-bottom'
                            : 'object-bottom-left'}"
                      />
                    {:else}
                      <h1
                        in:fly={{
                          y: 20,
                          duration: 1000,
                          delay: 100,
                          easing: cubicOut,
                        }}
                        class="line-clamp-2 text-3xl font-black tracking-tighter drop-shadow-2xl md:text-5xl md:leading-[1.1] lg:text-6xl"
                      >
                        {displayTitle}
                      </h1>
                    {/if}
                  </div>

                  <!-- Metadata Row -->
                  <div
                    in:fly={{
                      y: 20,
                      duration: 1000,
                      delay: 200,
                      easing: cubicOut,
                    }}
                    class="mt-2 flex flex-wrap items-center gap-4 text-xs font-medium text-white md:mt-4 md:text-sm {getAlignmentClasses(
                      alignment,
                      'flex',
                    )}"
                  >
                    <span
                      class="flex items-center justify-center rounded-md border border-white/20 bg-white/10 px-2 py-1 text-[10px] leading-none font-bold tracking-wider uppercase backdrop-blur-md md:text-xs"
                    >
                      {isTV ? "Series" : "Movie"}
                    </span>
                    {#if certifications[item.id] ?? (item.certification && item.certification !== "N/A")}
                      <span class="text-white/40">|</span>
                      <span
                        class="flex items-center justify-center rounded-sm border border-white/40 px-1.5 py-1 text-[10px] leading-none font-bold tracking-wider uppercase md:text-xs"
                      >
                        {certifications[item.id] ?? item.certification}
                      </span>
                    {/if}
                    <span class="text-white/40">|</span>
                    <span class="text-white drop-shadow-md"
                      >{getSeasonAndYear(
                        item.release_date ?? item.first_air_date ?? "",
                      )}</span
                    >
                    {#if item.original_language}
                      <span class="text-white/40">|</span>
                      <span class="text-white uppercase drop-shadow-md"
                        >{item.original_language}</span
                      >
                    {/if}
                    {#if ratings[item.id]?.scores?.length}
                      <div class="ml-2 flex items-center gap-4">
                        {#each ratings[item.id]?.scores as score (score.name)}
                          <!-- eslint-disable-next-line svelte/no-navigation-without-resolve -->
                          <a
                            href={score.url}
                            target="_blank"
                            rel="external noopener noreferrer"
                            class="flex items-center gap-1.5 transition-opacity hover:opacity-80"
                            title={score.name}
                          >
                            {#if score.image}
                              <img
                                src="/rating-logos/{score.image}"
                                alt={score.name}
                                class="h-4 w-auto object-contain"
                              />
                            {/if}
                            <span
                              class="text-xs font-bold text-white drop-shadow-md"
                              >{score.score}</span
                            >
                          </a>
                        {/each}
                      </div>
                    {:else if item.vote_average}
                      <span class="text-white/40">|</span>
                      <span
                        class="flex items-center font-bold text-white drop-shadow-md"
                      >
                        <Star
                          class="mr-1 h-3.5 w-3.5 fill-current text-yellow-500"
                        />
                        {item.vote_average.toFixed(1)}
                      </span>
                    {/if}
                  </div>

                  <!-- Overview -->
                  {#if item.overview}
                    <p
                      in:fly|global={{
                        y: 20,
                        duration: 1000,
                        delay: 300,
                        easing: cubicOut,
                      }}
                      class="mt-3 line-clamp-2 max-w-xl text-xs leading-relaxed text-white/90 drop-shadow-md md:mt-4 md:text-base"
                    >
                      {item.overview}
                    </p>
                  {/if}

                  <!-- Genres -->
                  {#if item.genre_ids?.length}
                    <div
                      in:fly|global={{
                        y: 20,
                        duration: 1000,
                        delay: 400,
                        easing: cubicOut,
                      }}
                      class="mt-4 flex flex-wrap gap-2 md:mt-6 {getAlignmentClasses(
                        alignment,
                        'flex',
                      )}"
                    >
                      {#each item.genre_ids.slice(0, 4) as genreId (genreId)}
                        {#if TMDB_GENRES[genreId]}
                          <div
                            class="rounded-full border border-white/20 bg-white/10 px-3 py-1 text-xs font-medium text-white backdrop-blur-md transition-colors hover:bg-white/20"
                          >
                            {TMDB_GENRES[genreId]}
                          </div>
                        {/if}
                      {/each}
                    </div>
                  {/if}

                  <!-- Action Buttons -->
                  <div
                    in:fly={{
                      y: 20,
                      duration: 1000,
                      delay: 500,
                      easing: cubicOut,
                    }}
                    class="mt-6 flex flex-wrap gap-4 md:mt-8 {getAlignmentClasses(
                      alignment,
                      'flex',
                    )}"
                  >
                    {#if showRequestButton}
                      <Button
                        href="/watch/{item.id}"
                        variant="default"
                        size="lg"
                        class="bg-primary text-primary-foreground hover:bg-primary/90 flex h-10 items-center justify-center rounded-md px-8 text-sm font-bold shadow-sm transition-all hover:scale-[1.02] md:h-12 md:text-base"
                      >
                        Play Now
                      </Button>
                    {/if}
                    <Button
                      variant="secondary"
                      size="lg"
                      href="/details/media/{item.id}/{mediaType}"
                      class="flex h-10 items-center justify-center rounded-md border border-white/10 bg-white/10 px-8 text-sm font-bold text-white shadow-sm backdrop-blur-md transition-all hover:scale-[1.02] hover:bg-white/20 md:h-12 md:text-base"
                    >
                      More Info
                    </Button>
                  </div>
                </div>
              </div>
            {/key}
          </Carousel.Item>
        {/each}
      </Carousel.Content>
    </Carousel.Root>

    <!-- Navigation Arrows (only align left/right correctly) -->
    <div
      class="pointer-events-none absolute inset-0 z-20 flex items-center justify-between px-4"
    >
      <button
        class="pointer-events-auto hidden h-12 w-12 items-center justify-center rounded-full border border-white/10 bg-black/20 text-white/70 backdrop-blur-md transition-all hover:scale-110 hover:bg-black/40 hover:text-white md:flex"
        onclick={() => api?.scrollPrev()}
        aria-label="Previous slide"
      >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
          class="h-6 w-6"
        >
          <polyline points="15 18 9 12 15 6"></polyline>
        </svg>
      </button>
      <button
        class="pointer-events-auto hidden h-12 w-12 items-center justify-center rounded-full border border-white/10 bg-black/20 text-white/70 backdrop-blur-md transition-all hover:scale-110 hover:bg-black/40 hover:text-white md:flex"
        onclick={() => api?.scrollNext()}
        aria-label="Next slide"
      >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
          class="h-6 w-6"
        >
          <polyline points="9 18 15 12 9 6"></polyline>
        </svg>
      </button>
    </div>

    <!-- Progress Indicator -->
    <div
      class="absolute bottom-4 left-1/2 z-20 flex max-w-[calc(100%-2rem)] -translate-x-1/2 items-center gap-4 rounded-full border border-white/10 bg-black/30 px-4 py-2 backdrop-blur-xl md:px-6 md:py-2.5"
    >
      <span
        class="font-mono text-xs font-medium whitespace-nowrap text-white/90"
        >{currentIndex + 1} / {data.length}</span
      >

      <!-- Desktop Segmented Progress (Hidden until Large screens) -->
      <div class="hidden gap-1.5 lg:flex">
        {#each data.map((__, idx) => idx) as i (i)}
          <button
            class="relative h-1 w-6 cursor-pointer overflow-hidden rounded-full transition-all duration-300 {i ===
            currentIndex
              ? 'bg-white/20'
              : 'bg-white/20 hover:bg-white/40'}"
            onclick={() => api?.scrollTo(i)}
            aria-label="Go to slide {i + 1}"
          >
            {#if i === currentIndex}
              <div
                class="animate-progress bg-primary absolute top-0 bottom-0 left-0"
              ></div>
            {/if}
          </button>
        {/each}
      </div>

      <!-- Mobile/Tablet Simple Progress Bar -->
      <div class="h-1 w-32 overflow-hidden rounded-full bg-white/20 lg:hidden">
        <div
          class="bg-primary h-full transition-all duration-300 ease-out"
          style="width: {((currentIndex + 1) / data.length) * 100}%"
        ></div>
      </div>
    </div>
  </div>
{:else}
  <div class="relative w-full overflow-hidden rounded-2xl {heightClass}">
    <div
      class="from-background to-muted absolute inset-0 animate-pulse bg-linear-to-t"
    ></div>

    <div class="absolute inset-0 z-2 flex flex-col justify-end p-8 md:p-12">
      <div class="w-full max-w-xl">
        <Skeleton class="mb-3 h-12 w-3/4" />
        <div class="flex items-center gap-3">
          <Skeleton class="h-5 w-16" />
          <Skeleton class="h-5 w-24" />
          <Skeleton class="h-5 w-12" />
        </div>
        <Skeleton class="mt-4 h-4 w-full" />
        <Skeleton class="mt-2 h-4 w-4/5" />
        <div class="mt-4 flex gap-2">
          <Skeleton class="h-7 w-20 rounded-full" />
          <Skeleton class="h-7 w-24 rounded-full" />
        </div>
        <div class="mt-6 flex gap-3">
          <Skeleton class="h-11 w-28" />
          <Skeleton class="h-11 w-32" />
        </div>
      </div>
    </div>
  </div>
{/if}

<style>
  @keyframes progress {
    from {
      width: 0%;
    }
    to {
      width: 100%;
    }
  }
  .animate-progress {
    animation: progress 5s linear;
  }
</style>

// apps/frontend/components/tmdb-now-playing/tmdb-now-playing.tsx
import { cn } from "cn";
import Autoplay from "embla-carousel-autoplay";
import Fade from "embla-carousel-fade";
import { Star } from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import React, { startTransition, useEffect, useState } from "react";
import { useHoverDirty } from "react-use";

import { Button } from "../_ui/button";
import { Carousel, CarouselContent, CarouselItem } from "../_ui/carousel";
import { getAlignmentClasses } from "./_utilities/get-alignment-classes";
import { TmdbNowPlayingSkeleton } from "./tmdb-now-playing-skeleton";

import type { CarouselApi } from "../_ui/carousel";
import type { RefObject } from "react";

const TMDB_GENRES: Record<number, string> = {
  28: "Action",
  12: "Adventure",
  16: "Animation",
  35: "Comedy",
  80: "Crime",
  99: "Documentary",
  18: "Drama",
  10_751: "Family",
  14: "Fantasy",
  36: "History",
  27: "Horror",
  10_402: "Music",
  9648: "Mystery",
  10_749: "Romance",
  878: "Sci-Fi",
  10_770: "TV Movie",
  53: "Thriller",
  10_752: "War",
  37: "Western",
  10_759: "Action & Adventure",
  10_762: "Kids",
  10_763: "News",
  10_764: "Reality",
  10_765: "Sci-Fi & Fantasy",
  10_766: "Soap",
  10_767: "Talk",
  10_768: "War & Politics",
};

export interface TMDBNowPlayingItem {
  id: number;
  mediaType?: "movie" | "tv" | "person" | "company";
  title?: string;
  name?: string;
  backdropPath?: string | null;
  releaseDate?: string;
  firstAirDate?: string;
  voteAverage?: number | null;
  originalLanguage?: string;
  overview?: string;
  genreIds?: number[];
  certification?: string;
}

export interface TmdbNowPlayingProps {
  data?: TMDBNowPlayingItem[];
  showRequestButton?: boolean;
  alignment?: "left" | "center" | "right";
  heightClass?: string;
}

export function TmdbNowPlaying({
  data,
  showRequestButton = true,
  alignment = "left",
  heightClass = "h-[350px] md:h-[420px]",
}: TmdbNowPlayingProps) {
  const autoplayDelay = 5000;
  const autoplayPlugin = Autoplay({
    delay: autoplayDelay,
    stopOnMouseEnter: true,
  });

  const fadePlugin = Fade();

  const [currentIndex, setCurrentIndex] = useState(0);

  const [certifications, setCertifications] = useState<
    Record<number, string | null>
  >({});

  const [ratings, setRatings] = useState<
    Record<
      number,
      {
        scores?: { name: string; image?: string; score: string; url: string }[];
      }
    >
  >({});

  const [logos, setLogos] = useState<Record<number, string | null>>({});

  const [api, setApi] = React.useState<CarouselApi>();
  const carouselRef = React.useRef<HTMLDivElement>(null);

  const isCarouselHovered = useHoverDirty(
    carouselRef as RefObject<Element>,
    Boolean(carouselRef.current),
  );

  useEffect(() => {
    if (!api) {
      return;
    }

    const { autoplay } = api.plugins();

    if (isCarouselHovered) {
      autoplay.stop();
    } else {
      autoplay.play();
    }
  }, [api, isCarouselHovered]);

  useEffect(() => {
    if (!api) {
      return;
    }

    api.plugins().autoplay.reset();
  }, [api, currentIndex]);

  useEffect(() => {
    if (!api) {
      return;
    }

    setCurrentIndex(api.selectedScrollSnap());

    api.on("select", () => {
      startTransition(() => {
        setCurrentIndex(api.selectedScrollSnap());
      });
    });
  }, [api]);

  if (!data || data.length === 0) {
    return <TmdbNowPlayingSkeleton />;
  }

  return (
    <div className="border-border/50 relative overflow-hidden rounded-2xl border shadow-2xl">
      <Carousel
        setApi={setApi}
        plugins={[autoplayPlugin, fadePlugin]}
        opts={{ duration: 40, loop: true }}
        className="relative"
        aria-label="Now playing movies carousel"
        ref={carouselRef}
      >
        <CarouselContent>
          {data.map((item, i) => {
            const isTV = item.mediaType === "tv";
            const mediaType = isTV ? "tv" : "movie";
            const displayTitle = item.title ?? item.name ?? "Untitled";
            const logo = logos[item.id];

            const backgroundGradient =
              "radial-gradient(120% 160% at 0% 100%, black 0%, transparent 70%), linear-gradient(to bottom, transparent 10%, black 100%)";

            function getAnimationClass(delay: number) {
              return i === currentIndex
                ? `animate-(--animate-fly-in) delay-${delay.toString()}`
                : "hidden";
            }

            return (
              <CarouselItem
                key={item.id}
                className={cn("relative w-full", heightClass)}
              >
                {item.backdropPath && (
                  <Image
                    src={item.backdropPath}
                    alt={displayTitle}
                    className="absolute h-full w-full object-cover object-top select-none"
                    loading="lazy"
                    fill
                  />
                )}

                <div
                  className="bg-background pointer-events-none absolute top-0 right-0 bottom-0 left-0"
                  style={{
                    WebkitMaskImage: backgroundGradient,
                    maskImage: backgroundGradient,
                  }}
                />

                <div
                  className={cn(
                    "absolute top-0 right-0 bottom-0 left-0 z-10 flex flex-col justify-end px-8 pt-2 pb-24 md:px-32 md:pt-8 md:pb-16 lg:right-0 lg:left-0",
                    getAlignmentClasses(alignment, "container"),
                  )}
                >
                  <div
                    className={cn(
                      "flex w-full max-w-3xl flex-col",
                      getAlignmentClasses(alignment, "flex"),
                    )}
                  >
                    <div
                      className={cn(
                        "mb-4 flex h-24 items-end",
                        getAlignmentClasses(alignment, "flex"),
                      )}
                    >
                      {logo ? (
                        <Image
                          src={logo}
                          alt={displayTitle}
                          className={cn(
                            "max-h-full max-w-[80%] object-contain drop-shadow-2xl",
                            alignment === "right"
                              ? "object-bottom-right"
                              : alignment === "center"
                                ? "object-bottom"
                                : "object-bottom-left",
                          )}
                        />
                      ) : (
                        <h1
                          className={cn(
                            "line-clamp-2 text-3xl font-black tracking-tighter drop-shadow-2xl md:text-5xl md:leading-[1.1] lg:text-6xl",
                            getAnimationClass(100),
                          )}
                        >
                          {displayTitle}
                        </h1>
                      )}
                    </div>
                    <div
                      className={cn(
                        "mt-2 flex flex-wrap items-center gap-4 text-xs font-medium text-white md:mt-4 md:text-sm",
                        getAlignmentClasses(alignment, "flex"),
                        getAnimationClass(200),
                      )}
                    >
                      <span className="flex items-center justify-center rounded-md border border-white/20 bg-white/10 px-2 py-1 text-[10px] leading-none font-bold tracking-wider uppercase backdrop-blur-md md:text-xs">
                        {isTV ? "Series" : "Movie"}
                      </span>
                      {(certifications[item.id] ??
                        (item.certification &&
                          item.certification !== "N/A")) && (
                        <>
                          <span className="text-white/40">|</span>
                          <span className="flex items-center justify-center rounded-sm border border-white/40 px-1.5 py-1 text-[10px] leading-none font-bold tracking-wider uppercase md:text-xs">
                            {certifications[item.id] ?? item.certification}
                          </span>
                        </>
                      )}
                      <span className="text-white/40">|</span>
                      <span className="text-white drop-shadow-md">
                        {/* {getSeasonAndYear(
                            item.releaseDate ?? item.firstAirDate ?? "",
                          )} */}
                      </span>
                      {item.originalLanguage && (
                        <>
                          <span className="text-white/40">|</span>
                          <span className="text-white uppercase drop-shadow-md">
                            {item.originalLanguage}
                          </span>
                        </>
                      )}
                      {ratings[item.id]?.scores?.length && (
                        <div className="ml-2 flex items-center gap-4">
                          {ratings[item.id]?.scores?.map((score) => (
                            <a
                              key={score.name}
                              href={score.url}
                              target="_blank"
                              rel="external noopener noreferrer"
                              className="flex items-center gap-1.5 transition-opacity hover:opacity-80"
                              title={score.name}
                            >
                              {score.image && (
                                <Image
                                  src={`/rating-logos/${score.image}`}
                                  alt={score.name}
                                  className="h-4 w-auto object-contain"
                                />
                              )}
                              <span className="text-xs font-bold text-white drop-shadow-md">
                                {score.score}
                              </span>
                            </a>
                          ))}
                        </div>
                      )}
                      {ratings[item.id]?.scores?.length === 0 &&
                        item.voteAverage && (
                          <>
                            {" "}
                            <span className="text-white/40">|</span>
                            <span className="flex items-center font-bold text-white drop-shadow-md">
                              <Star className="mr-1 h-3.5 w-3.5 fill-current text-yellow-500" />
                              {item.voteAverage.toFixed(1)}
                            </span>
                          </>
                        )}
                    </div>
                    {item.overview && (
                      <p
                        className={cn(
                          "mt-3 line-clamp-2 max-w-xl text-xs leading-relaxed text-white/90 drop-shadow-md md:mt-4 md:text-base",
                          getAnimationClass(300),
                        )}
                      >
                        {item.overview}
                      </p>
                    )}
                    {item.genreIds?.length && (
                      <div
                        className={cn(
                          "mt-4 flex flex-wrap gap-2 md:mt-6",
                          getAlignmentClasses(alignment, "flex"),
                          getAnimationClass(400),
                        )}
                      >
                        {item.genreIds.slice(0, 4).map(
                          (genreId) =>
                            TMDB_GENRES[genreId] && (
                              <div
                                key={genreId.toString()}
                                className="rounded-full border border-white/20 bg-white/10 px-3 py-1 text-xs font-medium text-white backdrop-blur-md transition-colors hover:bg-white/20"
                              >
                                {TMDB_GENRES[genreId]}
                              </div>
                            ),
                        )}
                      </div>
                    )}
                    <div
                      className={cn(
                        "mt-6 flex flex-wrap gap-4 md:mt-8",
                        getAlignmentClasses(alignment, "flex"),
                        getAnimationClass(500),
                      )}
                    >
                      {showRequestButton && (
                        <Button
                          variant="default"
                          size="lg"
                          className="bg-primary text-primary-foreground hover:bg-primary/90 flex h-10 items-center justify-center rounded-md px-8 text-sm font-bold shadow-sm transition-all hover:scale-[1.02] md:h-12 md:text-base"
                          type="button"
                        >
                          <Link href={`/watch/${item.id.toString()}`}>
                            Play Now
                          </Link>
                        </Button>
                      )}
                      <Button
                        variant="secondary"
                        size="lg"
                        className="flex h-10 items-center justify-center rounded-md border border-white/10 bg-white/10 px-8 text-sm font-bold text-white shadow-sm backdrop-blur-md transition-all hover:scale-[1.02] hover:bg-white/20 md:h-12 md:text-base"
                        type="button"
                      >
                        <Link
                          href={`/details/media/${item.id.toString()}/${mediaType}`}
                        >
                          More Info
                        </Link>
                      </Button>
                    </div>
                  </div>
                </div>
              </CarouselItem>
            );
          })}
        </CarouselContent>
      </Carousel>
      <div className="pointer-events-none absolute inset-0 z-20 flex items-center justify-between px-4">
        <button
          className="pointer-events-auto hidden h-12 w-12 items-center justify-center rounded-full border border-white/10 bg-black/20 text-white/70 backdrop-blur-md transition-all hover:scale-110 hover:bg-black/40 hover:text-white md:flex"
          onClick={() => api?.scrollPrev()}
          aria-label="Previous slide"
          type="button"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
            className="h-6 w-6"
          >
            <polyline points="15 18 9 12 15 6" />
          </svg>
        </button>
        <button
          className="pointer-events-auto hidden h-12 w-12 items-center justify-center rounded-full border border-white/10 bg-black/20 text-white/70 backdrop-blur-md transition-all hover:scale-110 hover:bg-black/40 hover:text-white md:flex"
          onClick={() => api?.scrollNext()}
          aria-label="Next slide"
          type="button"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
            className="h-6 w-6"
          >
            <polyline points="9 18 15 12 9 6" />
          </svg>
        </button>
      </div>
      <div className="absolute bottom-4 left-1/2 z-20 flex max-w-[calc(100%-2rem)] -translate-x-1/2 items-center gap-4 rounded-full border border-white/10 bg-black/30 px-4 py-2 backdrop-blur-xl md:px-6 md:py-2.5">
        <span className="font-mono text-xs font-medium whitespace-nowrap text-white/90">
          {currentIndex + 1} / {data.length}
        </span>

        {/* <!-- Desktop Segmented Progress (Hidden until Large screens) --> */}
        <div className="hidden gap-1.5 lg:flex">
          {data.map(({ id }, i) => (
            <button
              key={id}
              className={cn(
                "relative h-1 w-6 cursor-pointer overflow-hidden rounded-full transition-all duration-300",
                i === currentIndex
                  ? "bg-white/20"
                  : "bg-white/20 hover:bg-white/40",
              )}
              onClick={() => api?.scrollTo(i)}
              aria-label={`Go to slide ${(i + 1).toString()}`}
              type="button"
            >
              {i === currentIndex && (
                <div
                  className={cn(
                    !isCarouselHovered && "animate-progress",
                    "bg-primary absolute top-0 bottom-0 left-0",
                  )}
                />
              )}
            </button>
          ))}
          <style jsx>{`
            @keyframes progress {
              from {
                width: 0%;
              }

              to {
                width: 100%;
              }
            }

            .animate-progress {
              animation: progress ${(autoplayDelay / 1000).toString()}s linear;
            }
          `}</style>
        </div>

        {/* <!-- Mobile/Tablet Simple Progress Bar --> */}
        <div className="h-1 w-32 overflow-hidden rounded-full bg-white/20 lg:hidden">
          <div
            className="bg-primary h-full transition-all duration-300 ease-out"
            style={{
              width: `${(((currentIndex + 1) / data.length) * 100).toString()}%`,
            }}
          />
        </div>
      </div>
    </div>
  );
}
