// apps/frontend/src/lib/components/auth/password-change-form.svelte
<script lang="ts">
  import * as Form from "$lib/components/ui/form/index.js";
  import * as ButtonGroup from "$lib/components/ui/button-group/index.js";
  import { Button } from "$lib/components/ui/button/index.js";
  import type { SuperValidated } from "sveltekit-superforms";
  import {
    passwordChangeSchema,
    type PasswordChangeSchema,
  } from "$lib/schemas/auth";
  import { superForm } from "sveltekit-superforms";
  import { zod4Client } from "sveltekit-superforms/adapters";
  import { Input } from "$lib/components/ui/input/index.js";
  import Eye from "@lucide/svelte/icons/eye";
  import EyeOff from "@lucide/svelte/icons/eye-off";
  import { Switch } from "$lib/components/ui/switch/index.js";
  import { toast } from "svelte-sonner";
  import type { FsSuperForm } from "formsnap";
  import LoaderCircle from "@lucide/svelte/icons/loader-circle";
  import { page } from "$app/state";
  import FormBase from "./form-base.svelte";

  let {
    data,
  }: {
    data: SuperValidated<PasswordChangeSchema>;
  } = $props();

  // svelte-ignore state_referenced_locally
  const form = superForm(data, {
    validators: zod4Client(passwordChangeSchema),
  });

  const { form: formData, enhance, message, delayed } = form;

  const passwordVisibility = $state({
    oldPassword: false,
    newPassword: false,
    confirmNewPassword: false,
  });

  type PasswordFieldName = "oldPassword" | "newPassword" | "confirmNewPassword";

  function togglePasswordVisibility(field: keyof typeof passwordVisibility) {
    passwordVisibility[field] = !passwordVisibility[field];
  }

  $effect(() => {
    if ($message) {
      if (page.status >= 200 && page.status < 300) {
        toast.success($message);
      } else {
        toast.error($message);
      }
    }
  });
</script>

{#snippet passwordFormField(
  form: FsSuperForm<PasswordChangeSchema>,
  name: PasswordFieldName,
  title: string,
)}
  <Form.Field {form} {name}>
    <Form.Control>
      {#snippet children({ props })}
        <Form.Label>{title}</Form.Label>
        <ButtonGroup.Root class="w-full">
          <Input
            type={passwordVisibility[name] ? "text" : "password"}
            {...props}
            bind:value={$formData[name]}
          />
          <Button
            onclick={() => togglePasswordVisibility(name)}
            variant="outline"
            size="icon"
            aria-label="toggle password visibility"
          >
            {#if passwordVisibility[name]}
              <EyeOff />
            {:else}
              <Eye />
            {/if}
          </Button>
        </ButtonGroup.Root>
      {/snippet}
    </Form.Control>
    <Form.FieldErrors />
  </Form.Field>
{/snippet}

<FormBase
  title="Change Password"
  description="Update your account password to keep your account secure."
>
  {#snippet content()}
    <form method="POST" use:enhance action="?/passwordChange">
      {@render passwordFormField(form, "oldPassword", "Current Password")}
      {@render passwordFormField(form, "newPassword", "New Password")}
      {@render passwordFormField(
        form,
        "confirmNewPassword",
        "Confirm New Password",
      )}

      <Form.Field {form} name="revokeSessions" class="mt-4">
        <Form.Control>
          {#snippet children({ props })}
            <div class="flex items-center gap-2">
              <Switch {...props} bind:checked={$formData.revokeSessions} />
              <Form.Label for="revokeSessions"
                >Revoke all other sessions</Form.Label
              >
            </div>
          {/snippet}
        </Form.Control>
        <Form.FieldErrors />
      </Form.Field>
    </form>
  {/snippet}

  {#snippet footer()}
    <Form.Button
      variant="secondary"
      size="sm"
      disabled={$delayed}
      onclick={() => {
        form.submit();
      }}
    >
      {#if $delayed}
        <LoaderCircle class="mr-2 h-5 w-5 animate-spin" />
      {/if}
      Change Password
    </Form.Button>
  {/snippet}
</FormBase>

// apps/frontend/components/auth/password-change-form/password-change-form.tsx
import { Button } from "@/components/_ui/button";
import { ButtonGroup } from "@/components/_ui/button-group";
import { Field, FieldError, FieldLabel } from "@/components/_ui/field";
import { Input } from "@/components/_ui/input";
import { Switch } from "@/components/_ui/switch";

import { zodResolver } from "@hookform/resolvers/zod";
import { Eye, EyeOff, LoaderCircle } from "lucide-react";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { toast } from "sonner";

import { FormBase } from "../form-base/form-base";
import { PasswordChangeFormSchema } from "./password-change.form-schema";

import type { PasswordChangeFormValues } from "./password-change.form-schema";
import type { UseFormRegisterReturn } from "react-hook-form";

export function PasswordChangeForm() {
  const form = useForm({
    resolver: zodResolver(PasswordChangeFormSchema),
    defaultValues: {
      confirmNewPassword: "",
      currentPassword: "",
      newPassword: "",
      revokeSessions: false,
    },
  });

  const handleSubmit = form.handleSubmit((_data) => {
    // TODO: Implement password change logic here

    toast.success("Password changed successfully!");
  });

  const [passwordVisibility, setPasswordVisibility] = useState({
    currentPassword: false,
    newPassword: false,
    confirmNewPassword: false,
  });

  function togglePasswordVisibility(field: keyof typeof passwordVisibility) {
    setPasswordVisibility((prev) => ({
      ...prev,
      [field]: !prev[field],
    }));
  }

  function renderPasswordField(
    name: Extract<
      keyof PasswordChangeFormValues,
      "currentPassword" | "newPassword" | "confirmNewPassword"
    >,
    label: string,
    register: UseFormRegisterReturn,
  ) {
    return (
      <Field data-invalid={Boolean(form.formState.errors[name])}>
        <FieldLabel htmlFor={name}>{label}</FieldLabel>
        <ButtonGroup className="w-full">
          <Input
            {...register}
            id={name}
            type={passwordVisibility[name] ? "text" : "password"}
          />
          <Button
            onClick={() => {
              togglePasswordVisibility(name);
            }}
            variant="outline"
            size="icon"
            aria-label="toggle password visibility"
            type="button"
          >
            {passwordVisibility[name] ? <EyeOff /> : <Eye />}
          </Button>
        </ButtonGroup>
        <FieldError errors={[form.formState.errors[name]]} />
      </Field>
    );
  }

  return (
    <form
      onSubmit={(event) => void handleSubmit(event)}
      // method="POST"
      // action="?/passwordChange"
    >
      <FormBase
        title="Change Password"
        description="Update your account password to keep your account secure"
        content={
          <>
            {renderPasswordField(
              "currentPassword",
              "Current Password",
              form.register("currentPassword", { deps: "newPassword" }),
            )}
            {renderPasswordField(
              "newPassword",
              "New Password",
              form.register("newPassword", { deps: "currentPassword" }),
            )}
            {renderPasswordField(
              "confirmNewPassword",
              "Confirm New Password",
              form.register("confirmNewPassword", { deps: "newPassword" }),
            )}
            <Field className="mt-4">
              <div className="flex items-center gap-2">
                <Switch
                  {...form.register("revokeSessions")}
                  id="revokeSessions"
                  onCheckedChange={(checked) => {
                    form.setValue("revokeSessions", checked);
                  }}
                />
                <FieldLabel htmlFor="revokeSessions">
                  Revoke all other sessions
                </FieldLabel>
              </div>
              <FieldError errors={[form.formState.errors.revokeSessions]} />
            </Field>
          </>
        }
        footer={
          <Button
            variant="secondary"
            size="sm"
            disabled={!form.formState.isDirty || form.formState.isSubmitting}
            type="submit"
          >
            {form.formState.isSubmitting && (
              <LoaderCircle className="mr-2 h-5 w-5 animate-spin" />
            )}
            Change Password
          </Button>
        }
      />
    </form>
  );
}
