// apps/frontend/components/auth/form-base/form-base.tsx
import { cn } from "@/lib/utils";

import type { ReactNode } from "react";

export interface FormBaseProps extends Pick<
  React.HTMLAttributes<HTMLDivElement>,
  "className"
> {
  content: ReactNode;
  description: string;
  footer?: ReactNode;
  title: string;
}

export function FormBase({
  content,
  description,
  footer,
  className,
  title,
}: FormBaseProps) {
  return (
    <section
      className={cn(
        "border-border/60 grid gap-4 border-b py-6 md:grid-cols-[12rem_minmax(0,1fr)]",
        className,
      )}
    >
      <div>
        <h2 className="text-base font-semibold">{title}</h2>
        {description && (
          <p className="text-muted-foreground mt-1 text-sm">{description}</p>
        )}
      </div>
      <div className="min-w-0">
        {content}
        {footer && <div className="mt-4">{footer}</div>}
      </div>
    </section>
  );
}

// apps/frontend/src/lib/components/auth/form-base.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import { cn } from "$lib/utils";

  interface Props {
    title: string;
    description?: string;
    class?: string;
    content: Snippet;
    footer?: Snippet;
  }

  let {
    title,
    description,
    class: className = "",
    content,
    footer,
  }: Props = $props();
</script>

<section
  class={cn(
    "border-border/60 grid gap-4 border-b py-6 md:grid-cols-[12rem_minmax(0,1fr)]",
    className,
  )}
>
  <div>
    <h2 class="text-base font-semibold">{title}</h2>
    {#if description}
      <p class="text-muted-foreground mt-1 text-sm">{description}</p>
    {/if}
  </div>

  <div class="min-w-0">
    {@render content()}

    {#if footer}
      <div class="mt-4">
        {@render footer()}
      </div>
    {/if}
  </div>
</section>
