// apps/frontend/components/auth/set-password-form/set-password-form.tsx
import { zodResolver } from "@hookform/resolvers/zod";
import { delay } from "es-toolkit";
import { Eye, EyeOff, LoaderCircle } from "lucide-react";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { toast } from "sonner";

import { ButtonGroup } from "#components/_ui/button-group.tsx";
import { Button } from "#components/_ui/button.tsx";
import { Field, FieldError, FieldLabel } from "#components/_ui/field.tsx";
import { Input } from "#components/_ui/input.tsx";
import { FormBase } from "#components/auth/form-base/form-base.tsx";

import { SetPasswordFormSchema } from "./set-password.form-schema.ts";

import type { SetPasswordFormValues } from "./set-password.form-schema.ts";
import type { UseFormRegisterReturn } from "react-hook-form";

export function SetPasswordForm() {
  const form = useForm({
    resolver: zodResolver(SetPasswordFormSchema),
    defaultValues: {
      confirmNewPassword: "",
      newPassword: "",
    },
  });

  const handleSubmit = form.handleSubmit(async (_data) => {
    // TODO: Implement password change logic here

    await delay(1000);

    toast.success("Password set successfully!");
  });

  const [passwordVisibility, setPasswordVisibility] = useState({
    newPassword: false,
    confirmNewPassword: false,
  });

  function togglePasswordVisibility(field: keyof typeof passwordVisibility) {
    setPasswordVisibility((prev) => ({
      ...prev,
      [field]: !prev[field],
    }));
  }

  function renderPasswordField(
    name: Extract<
      keyof SetPasswordFormValues,
      "newPassword" | "confirmNewPassword"
    >,
    label: string,
    register: UseFormRegisterReturn,
  ) {
    return (
      <Field data-invalid={Boolean(form.formState.errors[name])}>
        <FieldLabel htmlFor={name}>{label}</FieldLabel>
        <ButtonGroup className="w-full">
          <Input
            {...register}
            id={name}
            type={passwordVisibility[name] ? "text" : "password"}
          />
          <Button
            onClick={() => {
              togglePasswordVisibility(name);
            }}
            variant="outline"
            size="icon"
            aria-label="toggle password visibility"
            type="button"
          >
            {passwordVisibility[name] ? <EyeOff /> : <Eye />}
          </Button>
        </ButtonGroup>
        <FieldError errors={[form.formState.errors[name]]} />
      </Field>
    );
  }

  return (
    <form
      onSubmit={(event) => void handleSubmit(event)}
      // method="POST"
      // action="?/passwordChange"
    >
      <FormBase
        title="Set Password"
        description="Update your user profile information including username, name, and avatar."
        content={
          <>
            {renderPasswordField(
              "newPassword",
              "New Password",
              form.register("newPassword"),
            )}
            {renderPasswordField(
              "confirmNewPassword",
              "Confirm New Password",
              form.register("confirmNewPassword", { deps: "newPassword" }),
            )}
          </>
        }
        footer={
          <Button
            variant="secondary"
            size="sm"
            disabled={!form.formState.isDirty || form.formState.isSubmitting}
            type="submit"
          >
            {form.formState.isSubmitting && (
              <LoaderCircle className="mr-2 h-5 w-5 animate-spin" />
            )}
            Set Password
          </Button>
        }
      />
    </form>
  );
}

// apps/frontend/src/lib/components/auth/set-password-form.svelte
<script lang="ts">
  import * as Form from "$lib/components/ui/form/index.js";
  import * as ButtonGroup from "$lib/components/ui/button-group/index.js";
  import { Button } from "$lib/components/ui/button/index.js";
  import type { SuperValidated } from "sveltekit-superforms";
  import { setPasswordSchema, type SetPasswordSchema } from "$lib/schemas/auth";
  import { superForm } from "sveltekit-superforms";
  import { untrack } from "svelte";
  import { zod4Client } from "sveltekit-superforms/adapters";
  import { Input } from "$lib/components/ui/input/index.js";
  import Eye from "@lucide/svelte/icons/eye";
  import EyeOff from "@lucide/svelte/icons/eye-off";
  import { toast } from "svelte-sonner";
  import type { FsSuperForm } from "formsnap";
  import LoaderCircle from "@lucide/svelte/icons/loader-circle";
  import { page } from "$app/state";
  import FormBase from "./form-base.svelte";

  let {
    data,
  }: {
    data: SuperValidated<SetPasswordSchema>;
  } = $props();

  const form = untrack(() =>
    superForm(data, {
      validators: zod4Client(setPasswordSchema),
    }),
  );

  const { form: formData, enhance, message, delayed } = form;

  const passwordVisibility = $state({
    newPassword: false,
    confirmNewPassword: false,
  });

  type PasswordFieldName = "newPassword" | "confirmNewPassword";

  function togglePasswordVisibility(field: keyof typeof passwordVisibility) {
    passwordVisibility[field] = !passwordVisibility[field];
  }

  $effect(() => {
    if ($message) {
      if (page.status >= 200 && page.status < 300) {
        toast.success($message);
      } else {
        toast.error($message);
      }
    }
  });
</script>

{#snippet passwordFormField(
  form: FsSuperForm<SetPasswordSchema>,
  name: PasswordFieldName,
  title: string,
)}
  <Form.Field {form} {name}>
    <Form.Control>
      {#snippet children({ props })}
        <Form.Label>{title}</Form.Label>
        <ButtonGroup.Root class="w-full">
          <Input
            type={passwordVisibility[name] ? "text" : "password"}
            {...props}
            bind:value={$formData[name]}
          />
          <Button
            onclick={() => togglePasswordVisibility(name)}
            variant="outline"
            size="icon"
            aria-label="toggle password visibility"
          >
            {#if passwordVisibility[name]}
              <EyeOff />
            {:else}
              <Eye />
            {/if}
          </Button>
        </ButtonGroup.Root>
      {/snippet}
    </Form.Control>
    <Form.FieldErrors />
  </Form.Field>
{/snippet}

<FormBase
  title="Set Password"
  description="Update your user profile information including username, name, and avatar."
>
  {#snippet content()}
    <form method="POST" use:enhance action="?/setPassword">
      {@render passwordFormField(form, "newPassword", "New Password")}
      {@render passwordFormField(
        form,
        "confirmNewPassword",
        "Confirm New Password",
      )}
    </form>
  {/snippet}

  {#snippet footer()}
    <Form.Button
      variant="secondary"
      size="sm"
      disabled={$delayed}
      onclick={() => {
        form.submit();
      }}
    >
      {#if $delayed}
        <LoaderCircle class="mr-2 h-5 w-5 animate-spin" />
      {/if}
      Set Password
    </Form.Button>
  {/snippet}
</FormBase>
