// apps/frontend/src/lib/components/auth/email-change-form.svelte
<script lang="ts">
  import * as Form from "$lib/components/ui/form/index.js";
  import type { SuperValidated } from "sveltekit-superforms";
  import { emailChangeSchema, type EmailChangeSchema } from "$lib/schemas/auth";
  import { superForm } from "sveltekit-superforms";
  import { zod4Client } from "sveltekit-superforms/adapters";
  import { Input } from "$lib/components/ui/input/index.js";
  import { toast } from "svelte-sonner";
  import LoaderCircle from "@lucide/svelte/icons/loader-circle";
  import { page } from "$app/state";
  import FormBase from "./form-base.svelte";

  let {
    data,
  }: {
    data: SuperValidated<EmailChangeSchema>;
  } = $props();

  // svelte-ignore state_referenced_locally
  const form = superForm(data, {
    validators: zod4Client(emailChangeSchema),
  });

  const { form: formData, enhance, message, delayed } = form;

  $effect(() => {
    if ($message) {
      if (page.status >= 200 && page.status < 300) {
        toast.success($message);
      } else {
        toast.error($message);
      }
    }
  });
</script>

<FormBase
  title="Change Email"
  description="Manage your email address associated with your account."
>
  {#snippet content()}
    <form method="POST" use:enhance action="?/emailChange">
      <Form.Field {form} name="newEmail">
        <Form.Control>
          {#snippet children({ props })}
            <Form.Label for="newEmail">New Email</Form.Label>
            <Input
              type="email"
              placeholder="Your new email address"
              {...props}
              bind:value={$formData.newEmail}
            />
          {/snippet}
        </Form.Control>
        <Form.FieldErrors />
      </Form.Field>
    </form>
  {/snippet}

  {#snippet footer()}
    <Form.Button
      variant="secondary"
      size="sm"
      disabled={$delayed}
      onclick={() => {
        form.submit();
      }}
    >
      {#if $delayed}
        <LoaderCircle class="mr-2 h-5 w-5 animate-spin" />
      {/if}
      Change Email
    </Form.Button>
  {/snippet}
</FormBase>

// apps/frontend/components/auth/email-change-form/email-change-form.tsx
import { Button } from "@/components/_ui/button";
import {
  Field,
  FieldContent,
  FieldError,
  FieldLabel,
} from "@/components/_ui/field";
import { Input } from "@/components/_ui/input";
import { Label } from "@/components/_ui/label";

import { zodResolver } from "@hookform/resolvers/zod";
import { LoaderCircle } from "lucide-react";
import { FormProvider, useForm } from "react-hook-form";
import z from "zod";

import { FormBase } from "../form-base/form-base";

const EmailChangeFormSchema = z.object({
  newEmail: z.email(),
});

export function EmailChangeForm() {
  const form = useForm({
    resolver: zodResolver(EmailChangeFormSchema),
  });

  const { formState } = form;

  const handleSubmit = form.handleSubmit(async (data) => {
    await new Promise((resolve) => {
      setTimeout(resolve, 2000);
    });
  });

  return (
    <FormProvider {...form}>
      <form
        method="POST"
        onSubmit={(event) => {
          void handleSubmit(event);
        }}
        // action="?/emailChange"
      >
        <FormBase
          title="Change Email"
          description="Manage your email address associated with your account."
          content={
            <Field data-invalid={Boolean(formState.errors.newEmail)}>
              <FieldLabel className="flex-col items-start">
                New Email
                <FieldContent className="w-full">
                  <Input
                    {...form.register("newEmail")}
                    type="email"
                    placeholder="Your new email address"
                    required
                  />
                </FieldContent>
              </FieldLabel>
              <FieldError errors={[formState.errors.newEmail]} />
            </Field>
          }
          footer={
            <Button
              variant="secondary"
              size="sm"
              disabled={formState.isSubmitting}
              type="submit"
            >
              {formState.isSubmitting && (
                <LoaderCircle className="mr-2 h-5 w-5 animate-spin" />
              )}
              Change Email
            </Button>
          }
        />
      </form>
    </FormProvider>
  );
}
