// apps/frontend/src/lib/components/auth/account-links.svelte
<script lang="ts">
  import { Button } from "$lib/components/ui/button/index.js";
  import Link2 from "@lucide/svelte/icons/link-2";
  import Link2Off from "@lucide/svelte/icons/link-2-off";
  import { authClient } from "$lib/auth-client";
  import { toast } from "svelte-sonner";
  import { goto } from "$app/navigation";
  import { resolve } from "$app/paths";

  interface Account {
    id: string;
    providerId: string;
    createdAt: Date;
    updatedAt: Date;
    accountId: string;
    scopes: string[];
  }

  let {
    accounts,
    providers,
  }: {
    accounts: Account[];
    providers: Record<
      string,
      { enabled: boolean; disableSignup: boolean; name?: string; icon?: string }
    >;
  } = $props();

  // Built-in social providers that use linkSocial()
  // Plex is now a generic OAuth provider, so it's no longer in this list
  const builtInProviders: string[] = [];

  function isGenericOAuthProvider(providerId: string): boolean {
    return (
      !builtInProviders.includes(providerId) && providerId !== "credential"
    );
  }
</script>

<section
  class="border-border/60 grid gap-4 border-b py-6 md:grid-cols-[12rem_minmax(0,1fr)]"
>
  <div>
    <h2 class="text-base font-semibold">Account Links</h2>
    <p class="text-muted-foreground mt-1 text-sm">
      Manage your linked authentication providers.
    </p>
  </div>

  <div class="flex min-w-0 flex-col">
    {#each Object.entries(providers) as [providerId, config] (providerId)}
      {#if config.enabled && providerId !== "credential"}
        {@const providerName =
          config.name ||
          providerId.charAt(0).toUpperCase() + providerId.slice(1)}
        <div
          class="border-border/60 flex items-center justify-between border-t py-3"
        >
          <div class="flex items-center gap-2">
            {#if config.icon}
              <img
                src={config.icon}
                alt="{providerName} icon"
                class="h-4 w-4"
              />
            {/if}
            <span>{providerName}</span>
          </div>
          {#if accounts.find((account) => account.providerId === providerId)}
            <Button
              variant="destructive"
              size="sm"
              onclick={async () => {
                await authClient.unlinkAccount({
                  providerId: providerId,
                });
                toast.success(`${providerId} unlinked successfully.`);
                await goto(resolve("/auth"), { invalidateAll: true });
              }}
            >
              <Link2Off class="mr-2 h-4 w-4" />
              Unlink
            </Button>
          {:else}
            <Button
              size="sm"
              onclick={async () => {
                if (isGenericOAuthProvider(providerId)) {
                  // Use oauth2.link() for generic OAuth providers
                  await authClient.oauth2.link({
                    providerId: providerId,
                    callbackURL: "/auth",
                  });
                } else {
                  // Use linkSocial() for built-in social providers (plex)
                  await authClient.linkSocial({
                    provider: providerId,
                    callbackURL: "/auth",
                  });
                }
                toast.success(`${providerId} linked successfully.`);
              }}
            >
              <Link2 class="mr-2 h-4 w-4" />
              Link
            </Button>
          {/if}
        </div>
      {/if}
    {/each}
  </div>
</section>

// apps/frontend/components/auth/account-links/account-links.tsx
import { SingleAccountLink } from "./single-account-link";

import type { Account, Provider } from "./types";

export interface AccountLinksProps {
  accounts: Account[];
  providers: Record<string, Provider>;
}

export function AccountLinks({ accounts, providers }: AccountLinksProps) {
  return (
    <section className="border-border/60 grid gap-4 border-b py-6 md:grid-cols-[12rem_minmax(0,1fr)]">
      <div>
        <h2 className="text-base font-semibold">Account Links</h2>
        <p className="text-muted-foreground mt-1 text-sm">
          Manage your linked authentication providers.
        </p>
      </div>
      <div className="flex min-w-0 flex-col">
        {Object.entries(providers).map(([providerId, config]) => (
          <SingleAccountLink
            key={providerId}
            account={accounts.find(({ providerId: id }) => id === providerId)}
            providerId={providerId}
            provider={config}
          />
        ))}
      </div>
    </section>
  );
}
